instance_class: F2
runtime: python37
entrypoint: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --log-level warning

inbound_services:
- warmup

automatic_scaling:
  min_instances: 0
  max_instances: 3
  max_concurrent_requests: 10